// Cuts the twelve reminder illustrations from the author's sheet
//   illustrations/source/reminders-sheet.png  (4 × 3 panels, numbered, captions drawn in)
// and writes each one, paper keyed to transparent, colours kept:
//   extension/assets/illustrations/<id>.png        (≤ 520px wide, for the reminder card)
//   extension/assets/illustrations/<id>-icon.png   (192×192 on warm sand, for the system-notification fallback)
//   web/public/illustrations/reminders/<id>.png    (copy for the site)
// Run: node illustrations/scripts/reminders.mjs
// Tune BOXES if the sheet changes: [left, top, right, bottom] in source pixels, caption excluded.

import sharp from "sharp";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { crc32 } from "node:zlib";

const repo = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const SRC = join(repo, "illustrations", "source", "reminders-sheet.png");
const EXT = join(repo, "extension", "assets", "illustrations");
const WEB = join(repo, "web", "public", "illustrations", "reminders");
const SAND = "#F3E8D2";

// Reminder ids in sheet order (01 … 12).
export const IDS = [
  "breath-flow",
  "still-water",
  "returning-flow",
  "floating-leaf",
  "sun-and-air",
  "seated-presence",
  "moon-flow",
  "single-flow-line",
  "three-ripples",
  "wind-and-leaf",
  "organic-circle-person",
  "human-and-flow",
];

// Generous boxes around each drawing (number above and caption below excluded);
// the script trims to the ink inside them.
const BOXES = [
  [10, 70, 318, 272],
  [338, 70, 646, 320],
  [666, 70, 974, 296],
  [994, 70, 1302, 296],
  [10, 462, 318, 656],
  [338, 462, 646, 682],
  [666, 462, 974, 678],
  [994, 462, 1302, 664],
  [10, 850, 318, 1024],
  [338, 850, 646, 1024],
  [666, 850, 974, 1042],
  [994, 850, 1302, 992],
];

if (!existsSync(SRC)) {
  console.error(`Missing ${SRC}. Save the twelve-panel illustration sheet there, then run again.`);
  process.exit(1);
}
mkdirSync(EXT, { recursive: true });
mkdirSync(WEB, { recursive: true });

/** Make the paper transparent, keep every colour. Alpha comes from distance to the paper tone. */
async function keyPaper(pipeline) {
  const { data, info } = await pipeline.ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  // sample the paper from the corners
  const px = (x, y) => {
    const i = (y * info.width + x) * 4;
    return [data[i], data[i + 1], data[i + 2]];
  };
  const corners = [px(2, 2), px(info.width - 3, 2), px(2, info.height - 3), px(info.width - 3, info.height - 3)];
  const paper = [0, 1, 2].map((c) => corners.reduce((s, p) => s + p[c], 0) / 4);
  const out = Buffer.alloc(info.width * info.height * 4);
  for (let i = 0; i < info.width * info.height; i++) {
    const r = data[i * 4];
    const g = data[i * 4 + 1];
    const b = data[i * 4 + 2];
    const d = Math.sqrt((r - paper[0]) ** 2 + (g - paper[1]) ** 2 + (b - paper[2]) ** 2);
    // paper within ~14 units is fully transparent; ink and colour beyond ~70 fully opaque
    const a = Math.max(0, Math.min(1, (d - 14) / 56));
    out[i * 4] = r;
    out[i * 4 + 1] = g;
    out[i * 4 + 2] = b;
    out[i * 4 + 3] = Math.round(a * 255);
  }
  return sharp(out, { raw: { width: info.width, height: info.height, channels: 4 } });
}

function withProvenance(png, note) {
  const keyword = Buffer.from("impeccable:prompt\0", "latin1");
  const text = Buffer.from(
    `Cut from illustrations/source/reminders-sheet.png (the twelve-panel reminder sheet supplied by the author, generated by them with ChatGPT on 2026-09-17) by illustrations/scripts/reminders.mjs; paper keyed to transparent, colours kept; ${note}`,
    "latin1"
  );
  const data = Buffer.concat([keyword, text]);
  const type = Buffer.from("tEXt", "ascii");
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(Buffer.concat([type, data])) >>> 0);
  const chunk = Buffer.concat([len, type, data, crc]);
  const at = 8 + 25;
  return Buffer.concat([png.subarray(0, at), chunk, png.subarray(at)]);
}

let sheetCells = [];
for (let i = 0; i < IDS.length; i++) {
  const id = IDS[i];
  const [l, t, r, b] = BOXES[i];
  const keyed = await keyPaper(sharp(SRC).extract({ left: l, top: t, width: r - l, height: b - t }));
  const trimmed = await sharp(await keyed.png().toBuffer())
    .trim({ threshold: 12 })
    .extend({ top: 16, bottom: 16, left: 16, right: 16, background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toBuffer();
  const meta = await sharp(trimmed).metadata();
  const note = `panel ${String(i + 1).padStart(2, "0")} box ${[l, t, r, b].join(",")}, trimmed to ${meta.width}×${meta.height}`;
  writeFileSync(join(EXT, `${id}.png`), withProvenance(trimmed, note));
  writeFileSync(join(WEB, `${id}.png`), withProvenance(trimmed, note));
  // notification icon: the drawing filling a rounded warm-sand tile, so it
  // reads at the size the system shows it (the tile is the sticker's corner
  // language; a circle would force wide drawings small)
  const tight = await sharp(await keyed.png().toBuffer()).trim({ threshold: 12 }).png().toBuffer();
  const tile = Buffer.from(
    `<svg width="192" height="192" xmlns="http://www.w3.org/2000/svg"><rect width="192" height="192" rx="52" ry="52" fill="${SAND}"/></svg>`
  );
  const icon = await sharp({ create: { width: 192, height: 192, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } } })
    .composite([
      { input: tile, gravity: "centre" },
      { input: await sharp(tight).resize(172, 172, { fit: "inside" }).png().toBuffer(), gravity: "centre" },
    ])
    .png()
    .toBuffer();
  writeFileSync(join(EXT, `${id}-icon.png`), withProvenance(icon, `${note}; filling a 192×192 rounded warm-sand tile`));
  sheetCells.push({ id, buf: trimmed, w: meta.width, h: meta.height });
  console.log(`${id}: ${meta.width}×${meta.height}`);
}

// contact sheet for review
const cell = 220;
const comps = [];
for (let i = 0; i < sheetCells.length; i++) {
  const c = sheetCells[i];
  const fit = await sharp(c.buf).resize(cell - 20, cell - 20, { fit: "inside" }).png().toBuffer();
  const m = await sharp(fit).metadata();
  comps.push({
    input: fit,
    left: (i % 4) * cell + Math.round((cell - m.width) / 2),
    top: Math.floor(i / 4) * cell + Math.round((cell - m.height) / 2),
  });
}
await sharp({ create: { width: cell * 4, height: cell * 3, channels: 4, background: SAND } })
  .composite(comps)
  .png()
  .toFile(join(repo, ".impeccable", "review", "reminders-sheet.png"));
console.log("contact sheet: .impeccable/review/reminders-sheet.png");
